return {
  "stevearc/aerial.nvim",
  event = "LazyFile",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons",
  },
  keys = {
    { "<leader>cs", "<cmd>AerialToggle<CR>", desc = "Code symbols outline" },
    { "<leader>cS", "<cmd>AerialNavToggle<CR>", desc = "Code symbols nav" },
  },
  opts = {
    backends = { "lsp", "treesitter", "markdown" },
    layout = {
      default_direction = "prefer_right",
      max_width = { 40, 0.2 },
      min_width = 20,
      win_opts = { winblend = 0 },
    },
    attach_mode = "window",
    show_guides = true,
    guides = {
      mid_item = "├─",
      last_item = "└─",
      nested_top = "│ ",
      whitespace = "  ",
    },
    filter_kind = {
      "Class",
      "Constructor",
      "Enum", 
      "Function",
      "Interface",
      "Method",
      "Struct",
      "Variable",
    },
    icons = {
      Class = "󰠱 ",
      Function = "󰊕 ",
      Method = " ",
      Constructor = " ",
      Variable = "󰆧 ",
      Interface = " ",
      Struct = "󰌗 ",
      Enum = " ",
    },
    open_automatic = false,
    close_on_select = false,
    highlight_mode = "split_width",
    highlight_closest = true,
  },
}
