export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git fzf 1password brew fzf jira nvm ssh)

source $ZSH/oh-my-zsh.sh

source ~/.config/zsh/env.zsh
source ~/.config/zsh/alias.zsh


# pnpm
export PNPM_HOME="/Users/dormonzhou/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "/Users/dormonzhou/.bun/_bun" ] && source "/Users/dormonzhou/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
